UPDATE Defines SET Value = 3000 WHERE Name = 'ATTACK_SAME_STRENGTH_MIN_DAMAGE';
UPDATE Defines SET Value = 0 WHERE Name = 'ATTACK_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE';
UPDATE Defines SET Value = 3000 WHERE Name = 'RANGE_ATTACK_SAME_STRENGTH_MIN_DAMAGE';
UPDATE Defines SET Value = 0 WHERE Name = 'RANGE_ATTACK_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE';
UPDATE Defines SET Value = 3000 WHERE Name = 'INTERCEPTION_SAME_STRENGTH_MIN_DAMAGE';
UPDATE Defines SET Value = 0 WHERE Name = 'INTERCEPTION_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE';
UPDATE Defines SET Value = 3000 WHERE Name = 'AIR_STRIKE_SAME_STRENGTH_MIN_DEFENSE_DAMAGE';
UPDATE Defines SET Value = 0 WHERE Name = 'AIR_STRIKE_SAME_STRENGTH_POSSIBLE_EXTRA_DEFENSE_DAMAGE';